Update JenkinsFile

diff --git a/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile b/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
--- a/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
+++ b/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
@@ -9,18 +9,28 @@ pipeline {
     stages {
         stage('Checkout') {
             steps {
-                sh 'echo passed'
+                sh 'echo "Starting checkout..."'
                 checkout([$class: 'GitSCM', branches: [[name: 'main']], userRemoteConfigs: [[url: 'https://github.com/channammarani586/devops.git']]])
+                sh 'ls -ltr'
             }
         }
 
         stage('Build and Test') {
             steps {
-                sh 'ls -ltr'
-                sh '''
-                cd devops/java-maven-sonar-argocd-helm-k8s/spring-boot-app
-                mvn clean package
-                '''
+                script {
+                    def projectPath = "java-maven-sonar-argocd-helm-k8s/spring-boot-app"
+                    sh '''
+                    echo "Checking if project directory exists..."
+                    if [ -d "${WORKSPACE}/''' + projectPath + '''" ]; then
+                        cd ${WORKSPACE}/''' + projectPath + '''
+                        echo "Running Maven build..."
+                        mvn clean package
+                    else
+                        echo "ERROR: Project directory not found!"
+                        exit 1
+                    fi
+                    '''
+                }
             }
         }
 
@@ -30,14 +40,21 @@ pipeline {
             }
             steps {
                 script {
+                    def projectPath = "java-maven-sonar-argocd-helm-k8s/spring-boot-app"
                     sh '''
-                    cd devops/java-maven-sonar-argocd-helm-k8s/spring-boot-app
-                    docker build -t ${DOCKER_IMAGE} .
+                    if [ -d "${WORKSPACE}/''' + projectPath + '''" ]; then
+                        cd ${WORKSPACE}/''' + projectPath + '''
+                        echo "Building Docker image..."
+                        docker build -t ${DOCKER_IMAGE} .
+                        echo "Logging into Docker Hub..."
+                        docker login -u ${REGISTRY_CREDENTIALS_USR} -p ${REGISTRY_CREDENTIALS_PSW}
+                        echo "Pushing Docker image..."
+                        docker push ${DOCKER_IMAGE}
+                    else
+                        echo "ERROR: Project directory not found!"
+                        exit 1
+                    fi
                     '''
-                    
-                    docker.withRegistry('https://index.docker.io/v1/', 'docker-cred') {
-                        sh "docker push ${DOCKER_IMAGE}"
-                    }
                 }
             }
         }
@@ -50,11 +67,14 @@ pipeline {
             steps {
                 withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
                     sh '''
+                    echo "Configuring Git..."
                     git config --global user.email "sbiradarchannamma@gmail.com"
                     git config --global user.name "channammarani586"
-                    sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" devops/java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
-                    git add devops/java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
+                    echo "Updating Kubernetes deployment manifest..."
+                    sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
+                    git add java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
                     git commit -m "Update deployment image to version ${BUILD_NUMBER}"
+                    echo "Pushing changes to GitHub..."
                     git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME}.git HEAD:main
                     '''
                 }
@@ -65,8 +85,9 @@ pipeline {
             steps {
                 withCredentials([file(credentialsId: 'kubeconfig', variable: 'KUBECONFIG')]) {
                     sh '''
+                    echo "Deploying to Kubernetes..."
                     export KUBECONFIG=$KUBECONFIG
-                    kubectl apply -f devops/java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/
+                    kubectl apply -f java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/
                     '''
                 }
             }
